name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build Docker image
      run: docker build . -t ghcr.io/${{ github.repository }}:latest

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest
