name: CI Pipeline

on:
  # This will run the workflow on push or pull request to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubantu-latest
  
    steps:

    # Step 1: Check out the repository
    - name: Check out the code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installs dependencies
        pip install -r requirements-dev.txt

    # Step to run pytest tests with parallel execution
    - name: Run Pytest
      run: pytest -n auto --cov=note_api