name: Python Tests and Coverage

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=<specific_module_or_file> --cov-report=xml --numprocesses=auto  # Specify the module or file to test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true

      - name: Upload coverage report to GitHub Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Test run status
        run: |
          echo "Test run status: ${{ job.status }}"

  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    needs: test-and-coverage

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Run Snyk test
      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Make sure to set this secret in your repo
        run: snyk test --all-projects  # Removed the --debug flag
