name: Python Tests and Coverage

on: 
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Run tests with coverage
      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=./ --cov-report=xml --numprocesses=auto

      # Upload coverage to Codecov
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true

      # Upload coverage report as an artifact in GitHub Actions
      - name: Upload coverage report to GitHub Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      # Echo test run status
      - name: Test run status
        run: |
          echo "Test run status: ${{ job.status }}"
